language: php

php:
  - 5.4

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - extras/test.sh

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
